### PR TITLE
Touch up datasets and add tiny Covid dataset

### PR DESCRIPTION
**Pull request by basil-conto**
The first commit removes the single spurious trailing line from each of the two existing datasets. I think your code might need updating after this.

The second commit adds a tiny dataset with total COVID-19 cases by county. This dataset is too small to realistically use, and no other dataset I came across was both useful and in a simple format. But I felt like checking in this dataset anyway.  I can remove it altogether if you prefer.

### CODE REVIEW

**Review by imgo7 — COMMENTED** [review]
I have reviewed your changes on both branches. With regards to the datasets, my models do take into account the last line, thus your changes to the dataset files (theme_10_small_areas-education.csv and theme_15_small_areas-internet.csv) do affect my program. However, if you rename these changed datasets, you can use them for your model. 
I will reupload the datasets that I used for the logistic regression models, under their original names after you have renamed the datafiles and your contributions have been merged.
We will then have four datasets of Internet Access and Education which are slightly different (last line is absent for yours, present for mine,) but work with both of our programs.

**Comment by basil-conto** [comment]
> With regards to the datasets, my models do take into account the last line

Not really - your programs just discard it.

> thus your changes to the dataset files do affect my program.

I have now updated your programs to work regardless of the last line, please take a look.

> We will then have four datasets of Internet Access and Education which are slightly different

I'd really rather not duplicate 37k samples just because of 2 lines.

**Comment by imgo7** [comment]
I did not request you to change my programs. 
This project should enable both of our programs to work and in order for this to be done successfully it requires the inclusion of four datasets, then it should be done so to ensure full collaboration. 
We will present our work on two separate branches (blc/knn and code-and-data). I will write the location of our models on the report:
Logistic Regression = code-and-data branch 
KNN Regression = blc/knn branch 
I will also add this to the README.md on the main branch.

**Comment by basil-conto** [comment]
> This project should enable both of our programs to work and in order for this to be done successfully it requires the inclusion of four datasets, then it should be done so to ensure full collaboration.

But both of our programs can also work with the simple changes that I have made in this PR. This PR is fixing two bugs in your programs. Why include four copies of the dataset when only two are needed? I don't see how having different datasets "ensures full collaboration"; it sounds like the opposite of collaboration to me.

> We will present our work on two separate branches

Why? It's better to have all of our code on the same `main` branch. That is what is expected of and makes sense for group projects.

**Comment by imgo7** [comment]
I was surprised that you changed my contribution without asking for my opinion as it is group work. It is the last day and so to submit both of our contributions respectfully, we should submit what we have both done for the project, as it is a group task. Thus, to submit our point of views with respect we will show both branches as part of our submission, as the project report is required by the lecturer today.

**Comment by basil-conto** [comment]
> I was surprised that you changed my contribution without asking for my opinion as it is group work.

I have asked for your opinion in this PR twice without changing your contribution.

> Thus, to submit our point of views with respect we will show both branches as part of our submission

Even if you insist on rejecting my simple fixes, why can't all of our code be merged together on the `main` branch? I do not understand how that constitutes an issue.

**Pull request closed without merging**
